### ISSUE TITLE
[2.0] Deprecation - isViewFactory on view factory

### ISSUE THREAD

**Issue by mike-north** [yapplabs/ember-key-responder#22]
### Warning
```
"In Ember 2.0 view factories must have an `isViewFactory` property set to true.
You registered (subclass of Ember.View) as a view factory. Either add the `isViewFactory`
property to this factory or extend from Ember.View."
```

Line that throws this deprecation: https://github.com/yapplabs/ember-key-responder/blob/master/app/instance-initializers/key-responder.js#L15

**Comment by lukemelia** [comment]
OK to close this @mike-north ?

**Comment by mike-north** [comment]
Yep, I think so. Will re-open if I see anything else odd
