### ISSUE TITLE
Re-package without the `/tmp` dir (save 16 MiB of installed size).

### ISSUE THREAD

**Issue by ChALkeR** [yapplabs/ember-key-responder#24]
*Disclaimer: I do not use the package, this was found during automated npm packages downloading.*

See https://github.com/ember-cli/ember-cli/issues/4199 for details.
Atm, your npm package includes 16 MiB of garbage (about 65% of the total installed size) in the `/tmp` dir due to an already fixed bug in `ember-cli`.

This got fixed in this repo by f8e968587f5d810fb82201ed689d0386b9d86b4d, but no release has been made since then.

**Comment by lukemelia** [comment]
Hopefully this has been fixed since we released 4 days ago.
